DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS emp_role;
DROP TABLE IF EXISTS dept;

CREATE TABLE dept (
  dept_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  deptartment_name VARCHAR(75) NOT NULL
);

CREATE TABLE emp_role (
  role_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  role_title VARCHAR(100) NOT NULL
);

CREATE TABLE employees (
  emp_id INTEGER PRIMARY KEY AUTO_INCREMENT,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL
);